### ISSUE TITLE
Sending data to server from Raspberry Pi

### ISSUE THREAD

**Issue by yashasaxena** [jhoballah/Melanoma_JSY#1]
We wanted to start thinking about data transfer from the raspberry pi.
Right now, we are thinking we'll need to create an endpoint to post the data from the images to. 

Does it work the same way as it would when we run flask app locally? 

Is there a particular package we have to use to post data from raspberry pi to the server our service is being implemented on? 

Insights much appreciated!

**Comment by suyashkumar** [comment]
Hey @yashasaxena, happy to provide some thoughts!

So you have the right idea here that you would need to create an endpoint on a server to receive data from the Raspberry Pi (RPi) to get data off of the Pi. Ultimately what you would want to do is have a program running on the RPi client to acquire an image, transform that data into a base64 string (we talked about this process in class) and then POST that to a server URL. 

You will have two python programs here. One is the server program (the Flask application) which would run on your cloud server as per usual. You will then have a client python application running on the RPi. To issue RESTful API requests from your client python program, you can use the [requests](http://docs.python-requests.org/en/master/) library. 

Let me know if you have any other questions!

**Comment by yashasaxena** [comment]
Ok great thanks, I'll look into the requests library. 

As far as acquiring the image on the raspberry pi,
should we plan to save images on the raspberry pi sd card or use a separate USB SD card reader or some other method? 

appreciate the feedback

**Comment by suyashkumar** [comment]
You can pick whichever you would prefer--loading the images from a folder on the SD card (or any other media) is totally fine. It's just to simulate a "source" for the images (the folder could be replaced with a camera in the future or something)!

**Comment by suyashkumar** [comment]
So to clarify, as long as you have a program on your RPi that can read images from a folder, upload them to the server using a RESTful API, and successfully get a response, you are good on the RPi side! You should perhaps try to find a way to display the results as well, either using LEDs, a display, or something else!

**Comment by yashasaxena** [comment]
Alright, so referencing an issue brought up on our RFC regarding endpoint set up -->

If I'm posting the image data from the RPi to a server URL,
how can the data that was posted to that server URL be requested from a FLASK APP request?

@ad12 mentioned that we shouldn't have the same endpoint used in more than one request of the same type

I'm a little confused on how to go about this. The only thing that comes to mind is having the Raspberry Pi store the data in a non-local database, but I also don't know how to do that.
