### ISSUE TITLE
Travis CI 

### ISSUE THREAD

**Issue by ss842** [jhoballah/Melanoma_JSY#12]

**Comment by ss842** [comment]
@mlp6 and @suyashkumar : if we do not require Travis CI for our program, as we are using the web client and flask app on server side, do we still need to set up the integration? 

tagging @jhoballah so he is up to date on the response.

**Comment by mlp6** [comment]
If a given repo doesn't have any tests to run, then Travis CI does not have to just be arbitrarily set up!

**Comment by ss842** [comment]
yahoo, figured, but jhob wanted reassurance ;) thanks

**Comment by jhoballah** [comment]
It’s a constant fear of performing bad Git practices 😓

**Comment by mlp6** [comment]
Again, we're going to turn that frown upside down!
