### ISSUE TITLE
Flask App Testing - Send Image

### ISSUE THREAD

**Issue by yashasaxena** [jhoballah/Melanoma_JSY#21]
can utilize end point: http://vcm-1856.vm.duke.edu:5900/CloudMelanomaData_testing

write this endpoint in flask_app to retrieve image base 64 and re-encode it into an image
- simply return details about image (size) in JSON 
- verify image is same size from starting

in py command line:
convert image to base64

in postman: 
- submit this through Postman to above endpoint
- see what you get back

**Comment by ss842** [comment]
successfully completed
