### ISSUE TITLE
Docker/Flaskapp/Connection Refused - endpoint specification issue

### ISSUE THREAD

**Issue by ss842** [jhoballah/Melanoma_JSY#25]
![image](https://user-images.githubusercontent.com/31519918/33727257-7fa906d0-db45-11e7-904a-646cabb9ac94.png)

container : melanoma_jsy_instance1  - when running, URL successful 
container : testflask1 - when running, URL not found, unsecure connection, or connection refused

the difference in testflask1 is that there are now two files with if __name__=="__main__":         app.run(port="5900",host="0.0.0.0") and Dockerfile commands both to be run. one has @app.route('/') and the other has @app.route('/someendpoint'). have tried silencing one file vs the other (mains.py is identical to the one run with container melanoma_jsy_instance1) in Dockerfile, i have also tried taking out the endpoint specification because i know that worked in the melanoma_jsy_instance1 container. so i know it is not a conflicting name=main issue and it is not an endpoint specification issue (although that will be the next thing to figure out), but not sure why when the host is running, I cannot see results on the webpage. 

This is all in imgproc branch and using the vcm admin account

happy to chat in class, i'm sure this is not clear without visual aids

**Comment by mlp6** [comment]
Why is `host=0.0.0.0`?  That won't map to a valid, remotely-accessible address.

**Comment by ss842** [comment]
not sure how to answer "why", but, it worked for me on that first container a few days ago - and works again today when restarting that container 

issue #20

**Comment by jhoballah** [comment]
@mlp6 We did that because this is running on our VM, so we thought it should work based on this section from the setup dev server documentation. Would this still be a valid way of doing it?

"Setting the host to 0.0.0.0 tells flask to run the server locally but to allow external connections (from outside your remote machine) to make requests to your development server."

**Comment by ss842** [comment]
WELL 

I figured it out.

**Comment by ss842** [comment]
Issue had to do with creating the container - needed to specify/publish the ports in the command (include " -p 5900:5900"). noted it in issue #20 as important... then forgot to do it today. so, it's on me 

specifying endpoints is also working now, but only one CMD can be in the Dockerfile i believe?? need to ask about that. will add to issue #24
