### ISSUE TITLE
React App not running on VM: npm start error

### ISSUE THREAD

**Issue by jhoballah** [jhoballah/Melanoma_JSY#31]
Hi, I've been trying to set up the VM to run my React app for final testing. I've installed NPM and Node.js on the VM, as well as the other packages (such as Axios and Material-UI) that are needed for our web-client. For some reason, I still am getting an error when I try and run the app. My thoughts from the error log are that it's due to outdated NPM and Node.js versions. I've run commands to update NPM and Node.js, but the commands do not end up updating the version (but also do not raise any errors). 

Any thoughts on how to solve this? I've screenshotted the error log in case you find it useful.

![screen shot 2017-12-12 at 4 33 39 pm](https://user-images.githubusercontent.com/31487530/33889987-8a95aa80-df5a-11e7-8def-0071915da2a7.png)

**Comment by mlp6** [comment]
I will defer to the NodeJS master (a.k.a. @suyashkumar ), but I don't think that it is due to the "latest version" error message; that is a generic message that pops up for lots of errors.  Have you gotten this to work in a NodeJS environment on a different system other than your VM?

**Comment by jhoballah** [comment]
I do have it working correctly on my local machine, forgot to mention that!

**Comment by mlp6** [comment]
What version of NodeJS are you running locally?  You are using an older NodeJS on the VM...

**Comment by jhoballah** [comment]
Right, that's why I'm thinking it's an issue of the NodeJS not being the version on my local machine. However, even after running update commands that proceed without any errors on the VM, the versions do not end up updating. 

My local machine uses:
Nodejs  - 8.9.1
npm - 4.6.1

VM uses:
Nodejs - 4.2.6
npm - 3.5.2

**Comment by mlp6** [comment]
How did you install NodeJS on the VM?  I'm guessing you didn't use @suyashkumar https://github.com/suyashkumar/provision/blob/master/provision.sh  That would install v6.x; you could change https://github.com/suyashkumar/provision/blob/528b4cac11ec3b72279890f157f0d153e574be3b/provision.sh#L11 to specify using v8.x.

**Comment by jhoballah** [comment]
Ah, I hadn't seen that, thanks! I'll give the provision script from @suyashkumar a try in the morning as it's late in Beirut and update this issue afterwards if it's still unsuccessful. I had tried using the apt package manager in essentially the same way but noticed upon the error that my versions were not the ones I specified.

**Comment by jhoballah** [comment]
I just saw Suyash's e-mail about the Docker deployment process. All the commits related to our front-end have been on our reactapp branch of this repository, with associated Issues and Milestones (although all are now referenced as closed by commits in the reactapp branch, but have yet to be closed since the reactapp branch has not been merged to master). Would it be acceptable to simply create a new repo for the frontend and finalize deployment on that repo, or would you prefer us to merge the reactapp branch to master on this repository before removing those files and switching them to the Docker repository that Suyash updated?
Thanks!
@suyashkumar @mlp6

**Comment by jhoballah** [comment]
In essence, I wanted to make sure we were following good Git practices but I'm not sure what the best method would be for this...

**Comment by jhoballah** [comment]
Another thought, would it be better to fork our existing repo and add relevant parts of Suyash's repo, or would it instead be better to fork Suyash's repo and add the files that are relevant to our React app?

**Comment by jhoballah** [comment]
Bumping this in case it got lost among all the other issues!

**Comment by mlp6** [comment]
Swallowed up by student help requests.  Ahhh!

**Comment by jhoballah** [comment]
No worries, I'll be up for a while longer!

**Comment by jhoballah** [comment]
Managed to get it to work on the VM, once the React app related code was ready we did a pull request into master and then I forked @suyashkumar 's repo and added my code there into a dev branch. All set, no worries!
