### ISSUE TITLE
RFC Draft Feedback

### ISSUE THREAD

**Issue by jhoballah** [jhoballah/Melanoma_JSY#4]
Hi all, 

We were wondering if it might be possible to get some feedback on our RFC draft? The Google Doc link is below.

https://docs.google.com/document/d/1Wl9dSiEzq-uI_voJUDVcVedyqofK88Ei5nM1weHGDPQ/edit?usp=sharing

Thanks!

**Comment by suyashkumar** [comment]
Absolutely! Can you give suyashkumar2003@gmail.com and suyash@suyashkumar.com comment access?

**Comment by ss842** [comment]
@suyashkumar @ad12 - you both have editing access now!

**Comment by suyashkumar** [comment]
Perfect, gave it a quick review and it looks great (nice block diagrams!) -- certainly good enough to submit today/tomorrow, but I left a couple comments. More comments will come as we formally review the RFCs. Definitely consider how you want to leverage the database (do you want to store past exams for a patient?) and perhaps detail that out before starting. Do also detail out the API endpoints inputs/outputs as well, as knowing that before executing on the code is very useful. Feel free to comment and tag me in places in your RFC where you might have questions (just include +suyashkumar2003@gmail.com in the comment).
