### ISSUE TITLE
Docker Toolbox - local host refused to connect

### ISSUE THREAD

**Issue by ss842** [jhoballah/Melanoma_JSY#5]
Hi all, I went to office hours today with Arjun to catch up on the lecture with docker set up, since i have windows and didn't follow along on my computer then. we successfully got docker toolbox to work, but i am now having issues with seeing the image - 

![image](https://user-images.githubusercontent.com/31519918/33033598-f00b5122-cdf2-11e7-8634-7940441e30a8.png)

![image](https://user-images.githubusercontent.com/31519918/33033733-6d4f0200-cdf3-11e7-8ff7-50fd9a8d48c5.png)

does anything stick out here? do you have any lecture notes for this class? I didn't see anything in the repo but I could have missed it 

Thanks!
Sonali

**Comment by mlp6** [comment]
If you swing by my office, I can take a look w/ you.

**Comment by ss842** [comment]
ok walking over

**Comment by suyashkumar** [comment]
Hey folks, did this end up getting resolved? If not, let me know and I can continue to help out!

**Comment by ss842** [comment]
@suyashkumar - sorry for missing your comment! 

We decided to install docker on my vm instead, which worked but I am not able to access Ouwen's stuff
![image](https://user-images.githubusercontent.com/31519918/33281326-d083d376-d372-11e7-8133-dd689f5bebbf.png)

am i supposed to be inputting my vm ip address somewhere in that command? @mlp6 or @suyashkumar

**Comment by mlp6** [comment]
Try running that same command with `sudo` at the beginning.

**Comment by ss842** [comment]
ya i just noticed that and did so:

![image](https://user-images.githubusercontent.com/31519918/33281608-d7d6fe18-d373-11e7-9a0c-2d7024962df4.png)

**Comment by mlp6** [comment]
You don't want to use the URL: `localhost:8888`; you want to replace `localhost` with the IP address of your VM.  You should be able to get that using the command `/sbin/ifconfig`, which should yield something that starts with `152.16.XXX.XXX` or `152.3.XXX.XXX`.

**Comment by mlp6** [comment]
For example: `152.16.123.123:8888`

**Comment by ss842** [comment]
ah ok yes that is what i was thinking but wasn't sure of if i was right / how. will try that now

**Comment by mlp6** [comment]
Here is what my command output for the IP address yields:
```
mlp6@vcm-299:~$ /sbin/ifconfig
eth0      Link encap:Ethernet  HWaddr 00:50:56:a1:08:cc
          inet addr:152.3.64.186  Bcast:152.3.64.255  Mask:255.255.255.0
```
You want the address entry that shows up associated with `inet addr`.

**Comment by ss842** [comment]
ya i got it. phew. back on track 
![image](https://user-images.githubusercontent.com/31519918/33282061-6a87ed3e-d375-11e7-87c9-c86854baeda1.png)

**Comment by mlp6** [comment]
🕺
