### ISSUE TITLE
Create a Library of Suyash's Melanoma Repo 

### ISSUE THREAD

**Issue by ss842** [jhoballah/Melanoma_JSY#9]
create a library to be referenced in our program

**Comment by ss842** [comment]
@ad12 I want to create a submodule for Suyash's melanoma repo in our imgproc branch. would there be any issues with later merging this branch with others? We believe this should work but want to check before doing it. I also was looking into subtree (which would just be a snapshot, but that would work since we are not going to be working in suyash's repo, just taking its current state) and jawad mentioned forking the repo... what do you think would be best practice?

**Comment by mlp6** [comment]
That should work... I would stick with the submodule over subtree... subtree can create headaches (though it has a place).

**Comment by ss842** [comment]
ok thanks, will do.
